[project]
name = "botforbusiness"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.31.0",
    "aiosignal>=1.4.0",
    "aiosqlite>=0.22.1",
    "alembic>=1.19.1",
    "colorama>=0.4.6",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
]

[project.scripts]
main = "main:main"
